spring:
  security:
    client:
      registration:
        keycloak:
          client-id: pos-web-java
          client-secret: 2156cc22-2b4a-4f14-af73-7ef988873a8c
          clientName: Keycloak
          authorization-grant-type: authorization_code
          redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
      provider:
        keycloak:
          authorization-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/auth
          token-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/token
          user-info-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/userinfo
          jwk-set-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/certs
          user-name-attribute: preferred_username