spring:
  application:
    name: pos
  codec:
    max-in-memory-size: 200MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/pos
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/pos-web
          jwk-set-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/certs
#      client:
#        registration:
#          keycloak:
#            client-id: pos-web-java
#            client-secret: 2156cc22-2b4a-4f14-af73-7ef988873a8c
#            clientName: Keycloak
#            authorization-grant-type: authorization_code
#            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/certs
#            user-name-attribute: preferred_username
pos:
  feign:
    applyServiceBaseUrl: "localhost:8080/v1/apply"
    agentServiceBaseUrl: "localhost:8080/v1/agents"
server:
  port: 8081