pos:
  products:
    - code: ULAYF
      brochureUrl: link
    - code: ULINKED
      brochureUrl: link
    - code: HCARE
      brochureUrl: link
  documentRequirements:
    PASSPORT:
      type: PASSPORT
      group: IDENTIFICATION
      minimumUploads: 2
      maximumUploads: 2
    NATIONAL_ID:
      type: NATIONAL_ID
      group: IDENTIFICATION
      minimumUploads: 2
      maximumUploads: 2
    PAYMENT_RECEIPT:
      type: PAYMENT_RECEIPT
      group: RECEIPT
      minimumUploads: 2
      maximumUploads: 4
      forRoles:
        - PO
    BIRTH_CERTIFICATE:
      type: BIRTH_CERTIFICATE
      group: IDENTIFICATION
      minimumUploads: 2
      maximumUploads: 1
  acceptedFileTypes:
    - BMP
    - PNG
    - GIF
    - PDF
    - JPEG
    - TIFF
  maximumFileSize: 4
  documentUploadingRoles:
    - PO
    - IO
    - OI
