spring:
  data:
    mongodb:
      uri: mongodb://pos-db:27017/pos
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/pos-web
          jwk-set-uri: http://localhost:8080/auth/realms/pos-web/protocol/openid-connect/certs