spring:
  application:
    name: pos
  data:
    mongodb:
      uri: mongodb://localhost:27017/pos
pos:
  feign:
    applyServiceBaseUrl: "localhost:8080/apply"
    agentServiceBaseUrl: "localhost:8080/agents"