spring:
  profiles:
    active: secure
  application:
    name: pos
  codec:
    max-in-memory-size: 200MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/pos
pos:
  feign:
    applyServiceBaseUrl: "localhost:9000/v1/apply"
    agentServiceBaseUrl: "localhost:9000/v1/agents"
  auth:
    server:
      url: http://localhost:8080
server:
  port: 9000
