version: "3.9"
services:
  pos-db:
    image: mongo
    container_name: "pos-db"

    ports:
      - "27017:27017"
  pos-java:
    build:
      context: ../
    ports:
      - "9000:8081"
    depends_on:
      - pos-db
    container_name: pos-web-java
    environment:
      SPRING_PROFILES_ACTIVE: docker-local, local