apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-backing
  labels:
    ap.app: POS_BACKING
spec:
  replicas: 3
  selector:
    matchLabels:
      ap.app: POS_BACKING
  template:
    metadata:
      labels:
        ap.app: POS_BACKING
    spec:
      containers:
        - name: pos-config-java
          image: docker.io/library/pos-web-config-java
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
        - name: pos-keycloak
          image: bitnami/keycloak
          env:
            - name: KEYCLOAK_DATABASE_HOST
              value: 127.0.0.1:5432
            - name: KEYCLOAK_DATABASE_NAME
              value: pos_agents
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_DATABASE_USER
              value: pos
          ports:
            - containerPort: 8080
        - name: pos-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: pos_agents
            - name: POSTGRES_USER
              value: pos
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
        - name: pos-mongo
          image: mongo
          ports:
            - containerPort: 27018
---
apiVersion: v1
kind: Service
metadata:
  name: pos-backing-service
spec:
  selector:
    ap.app: POS_BACKING
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      name: keycloak
    - targetPort: 8081
      port: 8081
      name: config-server
#    - targetPort: 5432
#      port: 5432
#      name: pos-postgres
#      protocol: TCP
